buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Khai báo phiên bản Android Gradle Plugin khớp với môi trường build
        classpath 'com.android.tools.build:gradle:8.1.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
